apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: lanscape
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05"
      timezone: "Local"
  artifacts:
  - image: bang5:5000/lanscape_image
    sync:
      infer:
      - static/*
deploy:
  kubectl:
    manifests:
    - deploy.yaml
